### PR TITLE
Add Ukrainian files

### LINKED ISSUE #13: Ukrainian localization
Good afternoon. We have translated the LIZMAP project into Ukrainian on the transifex.com resource. Could you add Ukrainian (Ukraine) (uk_UA) localization to the repository?

### PR DESCRIPTION
**Pull request by Gustry**
* Ticket : Fix #13 
* Add Ukrainian config, I have also reviewed quickly the readme.

It should be backported to 3.5 and 3.4 I guess ?

### CODE REVIEW

**Comment by PalchikV** [comment]
Good afternoon. in which version will (uk_UA) be added? no problems with translation?

**Comment by Gustry** [comment]
We will make it for the next version 3.5.1 for sure ;-)
3.4.9 as well I think.

**Review by laurentj — APPROVED** [review]
r+

**Comment by PalchikV** [comment]
Hello everyone. Is there any news on the addition Ukrainian localization (uk_UA) ?)))

**Comment by Gustry** [comment]
@PalchikV I'm going to merge this PR.

However, it seems, you haven't translated the "Jelix framework".
https://www.transifex.com/3liz-1/jelix/languages/

Lizmap is using Jelix in the background.

**Comment by PalchikV** [comment]
Should we move Jelix to (uk_UA) first, and then localization will be added in the update?

**Pull request merged**
